services:

  postgres:
    image: postgres:17
    container_name: url-shortener-db
    restart: always

    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  springboot:

    build: .

    environment:
        - SPRING_PROFILES_ACTIVE=docker
    

    container_name: url-shortener-api
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - postgres


volumes:
  postgres_data: