spring.application.name=project


# spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true


