spring.application.name=project


# spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true


server.port=${PORT:8080}


# FROM eclipse-temurin:21-jdk AS builder

# WORKDIR /build


# FROM eclipse-temurin:21-jdk

# # Create non-root user and group, set workdir, copy app and ensure proper ownership
# RUN groupadd -r appuser && useradd -r -g appuser -d /app -s /sbin/nologin appuser
# WORKDIR /app
# COPY target/project-0.0.1-SNAPSHOT.jar app.jar
# RUN chown -R appuser:appuser /app

# EXPOSE 8080

# # Run as non-root user for safety
# USER appuser
# ENTRYPOINT ["java", "-jar", "app.jar"]

